org: ifrank2025
app: ifm-app

service: backend-nodejs


provider:
  name: aws
  runtime: nodejs20.x
  stage: dev
  region: us-east-1

functions: ${file(./src/serverless-config/dev/functions.yml)}


plugins:
  - serverless-offline

package:
  individually: true
  patterns:
    - '!node_modules/**'
    - '!.git/**'
    - '!**/*.ts'
    - '.build/**'